services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
